default: &default
  adapter: mysql2
  username: root
  password: password*8
  host: localhost
  port: 3306
  pool: 5
  timeout: 5000
  encoding: utf8

development:
  <<: *default
  database: fancy-retero_development

test:
  <<: *default
  database: fancy-retero_test